import 'dotenv/config'
import { PeriodeHoraire, PrismaClient } from '@prisma/client'

type HoraireInput = {
  periode: PeriodeHoraire
  jour: string
  heure_ouverture: string
  heure_fermeture: string
  ferme?: boolean
}

const prisma = new PrismaClient()

async function main() {
  // Clear all pool-related data before re-seeding.
  // This ensures a clean state every time the seed is run,
  // preventing duplicate entries. Order matters due to foreign key constraints.
  await prisma.horaireException.deleteMany()
  await prisma.horaireRegulier.deleteMany()
  await prisma.bassin.deleteMany()
  await prisma.avis.deleteMany()
  await prisma.favori.deleteMany()
  await prisma.piscine.deleteMany()

  // ─── Piscine 1 — Suzanne Berlioux ────────────────────────────────────────
  await prisma.piscine.create({
    data: {
      nom: 'Piscine Suzanne Berlioux',
      adresse: '10 place de la Rotonde, Forum des Halles',
      arrondissement: 1,
      latitude: 48.861944013677,
      longitude: 2.346556960766,
      description: 'En plein cœur des Halles, la piscine Suzanne Berlioux propose un bassin olympique de 50 mètres idéal pour perfectionner sa nage, dans le 1er arrondissement de Paris.',
      telephone: '+33182820169',
      email: 'contact@piscine-berlioux.fr',
      site_web: 'http://www.piscine-berlioux.fr/fr',
      acces_pmr: true,
      queer_friendly: false,
      accepte_passe_paris: false,
      is_open: true,
      espace_solarium: false,
      activites: ['Aquafitness', 'Aquabiking', 'Aquarunning', 'Aquapalm', 'Cours de natation'],
      images_galerie: [],
      prix_entree_normal: 5.10,
      prix_entree_reduit: 4.00,
      prix_carnet_normal: 46.00,
      prix_carnet_reduit: 36.00,
      prix_abonnement_normal: null,
      prix_abonnement_reduit: null,
      prix_brevet_natation: null,
      seche_cheveux: true,
      distributeur_equipements: true,
      casiers: true,
      vestiaires_mixtes: false,
      cabines_individuelles: false,
      douches_individuelles: false,
      douches_collectives: true,
      cabine_pmr: true,
      distributeur_boisson: true,
      bassins: {
        create: [{ nom: 'Bassin olympique', longueur: 50, largeur: 20, profondeur_min: null, profondeur_max: null, nb_couloirs: 8 }]
      },
      horaires_reguliers: {
        create: [
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '06:30', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '10:30', heure_fermeture: '23:30' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '12:00', heure_fermeture: '22:30' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '06:30', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '12:00', heure_fermeture: '23:30' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '12:00', heure_fermeture: '22:30' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '06:30', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '12:00', heure_fermeture: '23:30' },
          { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '09:00', heure_fermeture: '19:00' },
          { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '09:00', heure_fermeture: '19:00' },
          { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '06:30', heure_fermeture: '08:30' },
          { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '12:00', heure_fermeture: '22:30' },
          { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '06:30', heure_fermeture: '08:30' },
          { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '12:00', heure_fermeture: '23:30' },
          { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '12:00', heure_fermeture: '22:30' },
          { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '06:30', heure_fermeture: '08:30' },
          { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '12:00', heure_fermeture: '23:30' },
          { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '09:00', heure_fermeture: '19:00' },
          { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '09:00', heure_fermeture: '19:00' },
        ]
      }
    }
  })

  // ─── Piscine 2 — Marie-Marvingt ───────────────────────────────────────────
  await prisma.piscine.create({
    data: {
      nom: 'Piscine Marie-Marvingt',
      adresse: '16 rue du Renard',
      arrondissement: 4,
      latitude: 48.859114995626,
      longitude: 2.35249000711,
      description: 'Située à deux pas du centre Georges Pompidou, la piscine Marie-Marvingt dispose d\'un bassin de 25 mètres.',
      telephone: '+33142722945',
      email: null,
      site_web: null,
      acces_pmr: true,
      queer_friendly: false,
      accepte_passe_paris: true,
      is_open: true,
      espace_solarium: false,
      activites: ['Aquagym', 'Espace Paris Famille', 'École de natation'],
      images_galerie: [],
      prix_entree_normal: 3.50,
      prix_entree_reduit: 2.00,
      prix_carnet_normal: 28.00,
      prix_carnet_reduit: 16.00,
      prix_abonnement_normal: 43.00,
      prix_abonnement_reduit: 22.00,
      prix_brevet_natation: 7.00,
      seche_cheveux: true,
      distributeur_equipements: true,
      casiers: true,
      vestiaires_mixtes: false,
      cabines_individuelles: false,
      douches_individuelles: false,
      douches_collectives: true,
      cabine_pmr: true,
      distributeur_boisson: true,
      bassins: {
        create: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.60, profondeur_max: 2.00, nb_couloirs: null }]
      },
      horaires_reguliers: {
        create: [
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '11:30', heure_fermeture: '13:30' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '11:30', heure_fermeture: '13:30' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '13:30', heure_fermeture: '18:00' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '11:30', heure_fermeture: '13:30' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '16:30', heure_fermeture: '22:30' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '11:30', heure_fermeture: '13:30' },
          { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '22:30' },
          { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '10:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
        ]
      }
    }
  })

  // ─── Piscine 3 — Jean Taris ───────────────────────────────────────────────
  await prisma.piscine.create({
    data: {
      nom: 'Piscine Jean Taris',
      adresse: '16 rue Thouin',
      arrondissement: 5,
      latitude: 48.844744013084,
      longitude: 2.347994038066,
      description: 'La piscine Jean Taris est le lieu idéal pour se détendre à deux pas du Panthéon et des universités.',
      telephone: '0155428190',
      email: null,
      site_web: null,
      acces_pmr: false,
      queer_friendly: false,
      accepte_passe_paris: true,
      is_open: true,
      espace_solarium: false,
      activites: ['Aquagym', 'Natation loisirs', 'Plongée'],
      images_galerie: [],
      prix_entree_normal: 3.50,
      prix_entree_reduit: 2.00,
      prix_carnet_normal: 28.00,
      prix_carnet_reduit: 16.00,
      prix_abonnement_normal: 43.00,
      prix_abonnement_reduit: 22.00,
      prix_brevet_natation: 7.00,
      seche_cheveux: true,
      distributeur_equipements: true,
      casiers: false,
      vestiaires_mixtes: true,
      cabines_individuelles: false,
      douches_individuelles: false,
      douches_collectives: true,
      cabine_pmr: false,
      distributeur_boisson: false,
      bassins: {
        create: [
          { nom: "Bassin d'apprentissage", longueur: 15, largeur: 6, profondeur_min: 0.70, profondeur_max: 1.20, nb_couloirs: null },
          { nom: 'Grand bassin', longueur: 25, largeur: 15, profondeur_min: 1.30, profondeur_max: 3.00, nb_couloirs: null }
        ]
      },
      horaires_reguliers: {
        create: [
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '00:00', heure_fermeture: '00:00', ferme: true },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '09:00' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '11:30', heure_fermeture: '14:00' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '09:00' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '11:30', heure_fermeture: '18:00' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '09:00' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '11:30', heure_fermeture: '14:00' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '09:00' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '11:30', heure_fermeture: '14:00' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '17:00', heure_fermeture: '22:00' },
          { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '10:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '22:00' },
          { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
        ]
      }
    }
  })

  // ─── Piscine 4 — Espace Sportif Pontoise ──────────────────────────────────
  await prisma.piscine.create({
    data: {
      nom: 'Espace Sportif Pontoise',
      adresse: '19 rue de Pontoise',
      arrondissement: 5,
      latitude: 48.848968995199,
      longitude: 2.351425002493,
      description: 'Joyau de l\'architecture Art Déco des années 1930, classé monument historique. Propose un bassin de 33 mètres au cœur du Quartier latin.',
      telephone: '0780147861',
      email: 'contact@espace-sportif-pontoise-paris.fr',
      site_web: 'https://www.espace-sportif-pontoise-paris.fr/',
      acces_pmr: true,
      queer_friendly: false,
      accepte_passe_paris: false,
      is_open: true,
      espace_solarium: false,
      activites: ['Aquagym', 'Natation', 'Squash'],
      images_galerie: [],
      prix_entree_normal: 5.20,
      prix_entree_reduit: 3.10,
      prix_carnet_normal: 46.80,
      prix_carnet_reduit: 27.90,
      prix_abonnement_normal: 75.00,
      prix_abonnement_reduit: 36.00,
      prix_brevet_natation: 7.00,
      seche_cheveux: true,
      distributeur_equipements: true,
      casiers: true,
      vestiaires_mixtes: false,
      cabines_individuelles: true,
      douches_individuelles: true,
      douches_collectives: false,
      cabine_pmr: true,
      distributeur_boisson: true,
      bassins: {
        create: [{ nom: 'Bassin principal', longueur: 33, largeur: 15, profondeur_min: 1.40, profondeur_max: 2.80, nb_couloirs: 6 }]
      },
      horaires_reguliers: {
        create: [
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '06:30', heure_fermeture: '07:45' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '06:30', heure_fermeture: '07:45' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '06:30', heure_fermeture: '19:45' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '06:30', heure_fermeture: '07:45' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '11:45', heure_fermeture: '13:45' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '16:30', heure_fermeture: '19:45' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '20:00', heure_fermeture: '22:45' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '06:30', heure_fermeture: '07:45' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '11:45', heure_fermeture: '19:45' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '20:00', heure_fermeture: '22:45' },
          { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '09:00', heure_fermeture: '18:45' },
          { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '09:00', heure_fermeture: '18:45' },
          { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '06:30', heure_fermeture: '19:45' },
          { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '06:30', heure_fermeture: '19:45' },
          { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '06:30', heure_fermeture: '19:45' },
          { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '06:30', heure_fermeture: '19:45' },
          { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '06:30', heure_fermeture: '19:45' },
          { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '09:00', heure_fermeture: '18:45' },
          { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '09:00', heure_fermeture: '18:45' },
        ]
      }
    }
  })

  // ─── Piscine 5 — Saint-Germain ────────────────────────────────────────────
  await prisma.piscine.create({
    data: {
      nom: 'Piscine Saint-Germain',
      adresse: '12 rue Lobineau',
      arrondissement: 6,
      latitude: 48.851783009643,
      longitude: 2.335896018118,
      description: 'Près du carrefour de l\'Odéon, en sous-sol du marché Saint-Germain, cette piscine offre quelques instants de détente dans le cœur historique de Paris.',
      telephone: '+33156812540',
      email: null,
      site_web: null,
      acces_pmr: true,
      queer_friendly: false,
      accepte_passe_paris: true,
      is_open: true,
      espace_solarium: false,
      activites: ['Leçons de natation', 'École de natation', 'Aquagym'],
      images_galerie: [],
      prix_entree_normal: 3.50,
      prix_entree_reduit: 2.00,
      prix_carnet_normal: 28.00,
      prix_carnet_reduit: 16.00,
      prix_abonnement_normal: 43.00,
      prix_abonnement_reduit: 22.00,
      prix_brevet_natation: 7.00,
      seche_cheveux: true,
      distributeur_equipements: false,
      casiers: true,
      vestiaires_mixtes: true,
      cabines_individuelles: false,
      douches_individuelles: true,
      douches_collectives: false,
      cabine_pmr: false,
      distributeur_boisson: false,
      bassins: {
        create: [{ nom: 'Bassin principal', longueur: 25, largeur: 12.5, profondeur_min: 0.80, profondeur_max: 3.60, nb_couloirs: 5 }]
      },
      horaires_reguliers: {
        create: [
          { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '00:00', heure_fermeture: '00:00', ferme: true },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '08:45' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '11:30', heure_fermeture: '13:45' },
          { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '17:00', heure_fermeture: '21:30' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '08:45' },
          { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '11:30', heure_fermeture: '18:00' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '08:45' },
          { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '11:30', heure_fermeture: '13:45' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '08:45' },
          { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '11:30', heure_fermeture: '13:45' },
          { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '10:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '21:30' },
          { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
          { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
        ]
      }
    }
  })

  // ─── Helper : horaires standard municipaux (la majorité des piscines) ─────
  // Lun fermé / Mar-Ven 07-08:30 + 11:30-13:30 + 17-20 / Mer 07-18 / Sam-Dim 07-18
  const horairesMunicipaux = (periode: PeriodeHoraire) => {
    if (periode === 'SCOLAIRE') return [
      { periode, jour: 'Lundi',    heure_ouverture: '00:00', heure_fermeture: '00:00', ferme: true },
      { periode, jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
      { periode, jour: 'Mardi',    heure_ouverture: '11:30', heure_fermeture: '13:30' },
      { periode, jour: 'Mardi',    heure_ouverture: '17:00', heure_fermeture: '20:00' },
      { periode, jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
      { periode, jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
      { periode, jour: 'Jeudi',    heure_ouverture: '11:30', heure_fermeture: '13:30' },
      { periode, jour: 'Jeudi',    heure_ouverture: '17:00', heure_fermeture: '20:00' },
      { periode, jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '08:30' },
      { periode, jour: 'Vendredi', heure_ouverture: '11:30', heure_fermeture: '13:30' },
      { periode, jour: 'Vendredi', heure_ouverture: '17:00', heure_fermeture: '20:00' },
      { periode, jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
      { periode, jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
    ]
    return [
      { periode, jour: 'Lundi',    heure_ouverture: '10:00', heure_fermeture: '18:00' },
      { periode, jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '22:00' },
      { periode, jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
      { periode, jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
      { periode, jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '22:00' },
      { periode, jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
      { periode, jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
    ]
  }

  const tarifs = {
    prix_entree_normal: 3.50, prix_entree_reduit: 2.00,
    prix_carnet_normal: 28.00, prix_carnet_reduit: 16.00,
    prix_abonnement_normal: 43.00, prix_abonnement_reduit: 22.00,
    prix_brevet_natation: 7.00,
  }

  // ─── Piscines 6–42 ────────────────────────────────────────────────────────
  const piscines = [
    {
      nom: 'Piscine Jacqueline Auriol',
      adresse: '7 Allée Louis de Funès',
      arrondissement: 8,
      latitude: 48.874746047357, longitude: 2.308295331895,
      description: 'Piscine municipale du 8e arrondissement, dans le parc Monceau.',
      telephone: '+33153532333', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Georges Drigny',
      adresse: '18 rue Bochart de Saron',
      arrondissement: 9,
      latitude: 48.880990, longitude: 2.340050,
      description: 'Piscine municipale du 9e arrondissement.',
      telephone: '+33148780988', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Paul Valeyre',
      adresse: '37 rue de Rochechouart',
      arrondissement: 9,
      latitude: 48.879600, longitude: 2.345870,
      description: 'Piscine municipale du 9e, proche de la place Pigalle.',
      telephone: '+33148780596', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Catherine Lagatu',
      adresse: '155 avenue Parmentier',
      arrondissement: 10,
      latitude: 48.871379874257, longitude: 2.369896383667,
      description: 'Piscine du 10e arrondissement, accessible à tous types de handicap.',
      telephone: '+33142454428', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
      horaires_scolaire: [
        { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
        { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '11:30', heure_fermeture: '13:45' },
        { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '18:00', heure_fermeture: '22:30' },
        { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '08:30' },
        { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '11:30', heure_fermeture: '18:00' },
        { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '08:30' },
        { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '11:30', heure_fermeture: '13:30' },
        { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '16:30', heure_fermeture: '18:00' },
        { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '08:30' },
        { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '11:30', heure_fermeture: '13:30' },
        { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '16:30', heure_fermeture: '18:00' },
        { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
        { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
      ] as HoraireInput[],
      horaires_vacances: [
        { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '10:00', heure_fermeture: '18:00' },
        { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '22:30' },
        { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
        { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '18:00' },
        { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '18:00' },
        { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '07:00', heure_fermeture: '18:00' },
        { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '18:00' },
      ] as HoraireInput[],
    },
    {
      nom: 'Piscine Château Landon',
      adresse: '31 rue Château Landon',
      arrondissement: 10,
      latitude: 48.876770, longitude: 2.361830,
      description: 'Piscine municipale du 10e arrondissement.',
      telephone: '+33142052706', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Georges Rigal',
      adresse: '115 boulevard de Charonne',
      arrondissement: 11,
      latitude: 48.854210, longitude: 2.387600,
      description: 'Piscine municipale du 11e arrondissement.',
      telephone: '+33143730440', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine de la Cour des Lions',
      adresse: '7 rue de Pontoise',
      arrondissement: 12,
      latitude: 48.848100, longitude: 2.388200,
      description: 'Piscine municipale du 12e arrondissement.',
      telephone: '+33144675380', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Jean Boiteux',
      adresse: '74 avenue de la Porte de Vitry',
      arrondissement: 13,
      latitude: 48.816400, longitude: 2.368500,
      description: 'Piscine municipale du 13e arrondissement.',
      telephone: '+33145838320', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Roger Le Gall',
      adresse: '34 boulevard Carnot',
      arrondissement: 12,
      latitude: 48.843949064032, longitude: 2.415081394834,
      description: 'Piscine municipale du 12e arrondissement, proche du bois de Vincennes.',
      telephone: '+33144738112', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: true,
      activites: ['Natation', 'Aquagym', 'École de natation', 'Water-polo'],
      bassins: [
        { nom: 'Grand bassin', longueur: 50, largeur: 20, profondeur_min: 1.80, profondeur_max: 2.00, nb_couloirs: 8 },
        { nom: 'Bassin extérieur', longueur: 25, largeur: 15, profondeur_min: 0.80, profondeur_max: 1.80, nb_couloirs: 5 },
      ],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
      horaires_scolaire: [
        { periode: 'SCOLAIRE', jour: 'Lundi',    heure_ouverture: '07:00', heure_fermeture: '08:00' },
        { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '08:00' },
        { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '12:00', heure_fermeture: '14:00' },
        { periode: 'SCOLAIRE', jour: 'Mardi',    heure_ouverture: '17:00', heure_fermeture: '20:00' },
        { periode: 'SCOLAIRE', jour: 'Mercredi', heure_ouverture: '08:00', heure_fermeture: '21:00' },
        { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '08:00' },
        { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '12:00', heure_fermeture: '14:00' },
        { periode: 'SCOLAIRE', jour: 'Jeudi',    heure_ouverture: '17:00', heure_fermeture: '20:00' },
        { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '08:00' },
        { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '12:00', heure_fermeture: '14:00' },
        { periode: 'SCOLAIRE', jour: 'Vendredi', heure_ouverture: '17:00', heure_fermeture: '21:00' },
        { periode: 'SCOLAIRE', jour: 'Samedi',   heure_ouverture: '08:00', heure_fermeture: '21:00' },
        { periode: 'SCOLAIRE', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '19:00' },
      ] as HoraireInput[],
      horaires_vacances: [
        { periode: 'VACANCES', jour: 'Lundi',    heure_ouverture: '07:00', heure_fermeture: '20:00' },
        { periode: 'VACANCES', jour: 'Mardi',    heure_ouverture: '07:00', heure_fermeture: '20:00' },
        { periode: 'VACANCES', jour: 'Mercredi', heure_ouverture: '07:00', heure_fermeture: '20:00' },
        { periode: 'VACANCES', jour: 'Jeudi',    heure_ouverture: '07:00', heure_fermeture: '20:00' },
        { periode: 'VACANCES', jour: 'Vendredi', heure_ouverture: '07:00', heure_fermeture: '21:00' },
        { periode: 'VACANCES', jour: 'Samedi',   heure_ouverture: '08:00', heure_fermeture: '21:00' },
        { periode: 'VACANCES', jour: 'Dimanche', heure_ouverture: '08:00', heure_fermeture: '19:00' },
      ] as HoraireInput[],
    },
    {
      nom: 'Piscine de la Butte aux Cailles',
      adresse: '5 place Paul Verlaine',
      arrondissement: 13,
      latitude: 48.828657346203, longitude: 2.353020646317,
      description: 'Piscine Art Déco des années 1920 classée monument historique. Alimentée par une source naturelle, elle dispose d\'un bassin intérieur et d\'un bassin extérieur chauffé.',
      telephone: '+33145896005', email: null, site_web: null,
      acces_pmr: true, queer_friendly: true, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [
        { nom: 'Bassin intérieur', longueur: 25, largeur: 12, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 4 },
        { nom: 'Bassin extérieur', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 1.80, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: true, douches_collectives: false, cabine_pmr: true,
    },
    {
      nom: 'Piscine Dunois',
      adresse: '70 rue Dunois',
      arrondissement: 13,
      latitude: 48.829700, longitude: 2.365900,
      description: 'Piscine municipale du 13e arrondissement.',
      telephone: '+33145823760', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Château des Rentiers',
      adresse: '183 rue du Château des Rentiers',
      arrondissement: 13,
      latitude: 48.823800, longitude: 2.362100,
      description: 'Piscine municipale du 13e arrondissement.',
      telephone: '+33145856740', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Joséphine-Baker',
      adresse: 'Quai François Mauriac',
      arrondissement: 13,
      latitude: 48.835026823800, longitude: 2.376015745103,
      description: 'Piscine flottante sur la Seine, avec un toit escamotable qui s\'ouvre en été. Une expérience unique à Paris.',
      telephone: '+33156619650',
      email: 'contact@piscine-baker.fr',
      site_web: 'http://www.piscine-baker.fr',
      acces_pmr: false, queer_friendly: true, accepte_passe_paris: true,
      is_open: true, espace_solarium: true,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [
        { nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 4 },
        { nom: 'Pataugeoire', longueur: 15, largeur: 8, profondeur_min: 0.30, profondeur_max: 0.80, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Didot',
      adresse: '22 rue Mouton-Duvernet',
      arrondissement: 14,
      latitude: 48.828500, longitude: 2.320400,
      description: 'Piscine municipale du 14e arrondissement.',
      telephone: '+33145429196', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Aspirant Dunand',
      adresse: '20 rue Aspirant Dunand',
      arrondissement: 14,
      latitude: 48.824600, longitude: 2.316900,
      description: 'Piscine municipale du 14e arrondissement.',
      telephone: '+33145433400', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Thérèse et Jeanne Brulé',
      adresse: '12 allée Adrienne Bolland',
      arrondissement: 15,
      latitude: 48.838400, longitude: 2.279200,
      description: 'Piscine moderne du 15e arrondissement, ouverte en 2020.',
      telephone: '+33156080180', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [
        { nom: 'Grand bassin', longueur: 25, largeur: 15, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 5 },
        { nom: 'Bassin d\'apprentissage', longueur: 15, largeur: 8, profondeur_min: 0.40, profondeur_max: 1.20, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: true, douches_collectives: false, cabine_pmr: true,
    },
    {
      nom: 'Piscine La Plaine',
      adresse: '39 rue du Dr Babinsky',
      arrondissement: 17,
      latitude: 48.892400, longitude: 2.316800,
      description: 'Piscine municipale du 17e arrondissement.',
      telephone: '+33142278620', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Émile Anthoine',
      adresse: '9 rue Jean Rey',
      arrondissement: 15,
      latitude: 48.856800, longitude: 2.289300,
      description: 'Piscine municipale du 15e arrondissement, à proximité du Champ-de-Mars.',
      telephone: '+33145787263', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine René et André Mourlon',
      adresse: '8 avenue de la Porte Molitor',
      arrondissement: 16,
      latitude: 48.845800, longitude: 2.249100,
      description: 'Piscine Art Déco des années 1930 classée monument historique, dans le 16e arrondissement.',
      telephone: '+33146512690', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: true,
      activites: ['Natation', 'Aquagym', 'École de natation', 'Water-polo'],
      bassins: [
        { nom: 'Bassin intérieur', longueur: 33, largeur: 15, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 6 },
        { nom: 'Bassin extérieur', longueur: 33, largeur: 15, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 6 },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Blomet',
      adresse: '17 rue Blomet',
      arrondissement: 15,
      latitude: 48.844200, longitude: 2.308500,
      description: 'Piscine municipale du 15e arrondissement.',
      telephone: '+33145677060', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Keller',
      adresse: '14 rue de l\'Ingénieur Keller',
      arrondissement: 15,
      latitude: 48.848900, longitude: 2.283600,
      description: 'Piscine municipale du 15e arrondissement.',
      telephone: '+33148424196', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 50, largeur: 20, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 8 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Armand Massard',
      adresse: '66 boulevard du Montparnasse',
      arrondissement: 15,
      latitude: 48.843300, longitude: 2.316700,
      description: 'Piscine municipale du 15e, proche de la Tour Montparnasse.',
      telephone: '+33145484848', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: "Piscine d'Auteuil",
      adresse: '2 route des Lacs à Auteuil',
      arrondissement: 16,
      latitude: 48.847600, longitude: 2.254300,
      description: 'Piscine en plein air dans le bois de Boulogne, ouverte de mai à septembre.',
      telephone: '+33140717006', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: false, espace_solarium: true,
      activites: ['Natation', 'Aquagym'],
      bassins: [
        { nom: 'Grand bassin', longueur: 50, largeur: 20, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 8 },
        { nom: 'Bassin ludique', longueur: 25, largeur: 15, profondeur_min: 0.30, profondeur_max: 1.20, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Henry de Montherlant',
      adresse: '32 boulevard Lannes',
      arrondissement: 16,
      latitude: 48.864100, longitude: 2.261900,
      description: 'Piscine municipale du 16e arrondissement.',
      telephone: '+33140723520', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 33, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 6 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Bernard Lafay',
      adresse: '79 rue de la Jonquière',
      arrondissement: 17,
      latitude: 48.893900, longitude: 2.322100,
      description: 'Piscine municipale du 17e arrondissement.',
      telephone: '+33142287660', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Marjorie Gestring',
      adresse: '32 avenue de la Porte de Champerret',
      arrondissement: 17,
      latitude: 48.897600, longitude: 2.294800,
      description: 'Piscine municipale du 17e arrondissement, anciennement connue sous le nom Champerret.',
      telephone: '+33147633600', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Bertrand Dauvin',
      adresse: '8 rue René Binet',
      arrondissement: 18,
      latitude: 48.897200, longitude: 2.344800,
      description: 'Piscine municipale du 18e arrondissement.',
      telephone: '+33142233910', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Hébert',
      adresse: '2 rue des Fillettes',
      arrondissement: 18,
      latitude: 48.895400, longitude: 2.360200,
      description: 'Piscine municipale du 18e arrondissement.',
      telephone: '+33146074810', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 33, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 6 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine des Amiraux',
      adresse: '6 rue Hermann Lachapelle',
      arrondissement: 18,
      latitude: 48.893100, longitude: 2.352900,
      description: 'Chef-d\'œuvre Art Déco classé monument historique, conçu par Henri Sauvage en 1930. L\'une des plus belles piscines de Paris.',
      telephone: '+33146069226', email: null, site_web: null,
      acces_pmr: false, queer_friendly: true, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 33, largeur: 12, profondeur_min: 1.00, profondeur_max: 3.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Solita Salgado',
      adresse: '1 rue de Jessaint',
      arrondissement: 18,
      latitude: 48.885800, longitude: 2.357600,
      description: 'Piscine moderne du 18e arrondissement, ouverte en 2016.',
      telephone: '+33153264640', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [
        { nom: 'Grand bassin', longueur: 25, largeur: 15, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 5 },
        { nom: 'Bassin d\'apprentissage', longueur: 12, largeur: 8, profondeur_min: 0.40, profondeur_max: 1.10, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: true, douches_collectives: false, cabine_pmr: true,
    },
    {
      nom: 'Piscine Mathis',
      adresse: '4 rue Mathis',
      arrondissement: 19,
      latitude: 48.887200, longitude: 2.375800,
      description: 'Piscine municipale du 19e arrondissement.',
      telephone: '+33140380470', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Édouard Pailleron',
      adresse: '32 rue Édouard Pailleron',
      arrondissement: 19,
      latitude: 48.880516995482, longitude: 2.376390237441,
      description: 'Complexe sportif et culturel du 19e arrondissement. La piscine est classée dans un quartier d\'accessibilité augmentée.',
      telephone: '+33140402770',
      email: 'pailleron@vert-marine.com',
      site_web: 'http://www.pailleron19.com/',
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation', 'Plongeon'],
      bassins: [
        { nom: 'Grand bassin', longueur: 33, largeur: 15, profondeur_min: 1.00, profondeur_max: 3.00, nb_couloirs: 6 },
        { nom: 'Bassin d\'apprentissage', longueur: 15, largeur: 8, profondeur_min: 0.40, profondeur_max: 1.20, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Georges Hermant',
      adresse: '8 rue David d\'Angers',
      arrondissement: 19,
      latitude: 48.879300, longitude: 2.389400,
      description: 'Piscine municipale du 19e arrondissement.',
      telephone: '+33142003144', email: null, site_web: null,
      acces_pmr: false, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 10, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 4 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: false,
    },
    {
      nom: 'Piscine Rouvet',
      adresse: '9 rue Rouvet',
      arrondissement: 19,
      latitude: 48.890700, longitude: 2.388900,
      description: 'Piscine municipale du 19e arrondissement.',
      telephone: '+33140364140', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [{ nom: 'Bassin principal', longueur: 25, largeur: 12, profondeur_min: 0.80, profondeur_max: 2.00, nb_couloirs: 5 }],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Yvonne Godard',
      adresse: '7 rue du Plateau',
      arrondissement: 19,
      latitude: 48.874900, longitude: 2.381200,
      description: 'Piscine moderne du 19e arrondissement.',
      telephone: '+33140189680', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [
        { nom: 'Grand bassin', longueur: 25, largeur: 15, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 5 },
        { nom: 'Bassin d\'apprentissage', longueur: 12, largeur: 8, profondeur_min: 0.40, profondeur_max: 1.10, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: true, douches_collectives: false, cabine_pmr: true,
    },
    {
      nom: 'Piscine Georges Vallerey',
      adresse: '148 avenue Gambetta',
      arrondissement: 20,
      latitude: 48.868700, longitude: 2.405200,
      description: 'Piscine olympique du 20e arrondissement. Héberge régulièrement des compétitions nationales.',
      telephone: '+33140314700', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation', 'Water-polo', 'Natation synchronisée'],
      bassins: [
        { nom: 'Bassin olympique', longueur: 50, largeur: 21, profondeur_min: 2.00, profondeur_max: 2.00, nb_couloirs: 8 },
        { nom: 'Bassin d\'échauffement', longueur: 25, largeur: 12, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 5 },
      ],
      vestiaires_mixtes: false, cabines_individuelles: false, douches_individuelles: false, douches_collectives: true, cabine_pmr: true,
    },
    {
      nom: 'Piscine Alfred Nakache',
      adresse: '4-12 rue Dénoyez',
      arrondissement: 20,
      latitude: 48.871031137596, longitude: 2.379056852114,
      description: 'Piscine moderne du 20e arrondissement, dans le quartier de Belleville.',
      telephone: '+33158535780', email: null, site_web: null,
      acces_pmr: true, queer_friendly: false, accepte_passe_paris: true,
      is_open: true, espace_solarium: false,
      activites: ['Natation', 'Aquagym', 'École de natation'],
      bassins: [
        { nom: 'Grand bassin', longueur: 25, largeur: 15, profondeur_min: 1.00, profondeur_max: 2.00, nb_couloirs: 5 },
        { nom: 'Bassin d\'apprentissage', longueur: 12, largeur: 8, profondeur_min: 0.40, profondeur_max: 1.10, nb_couloirs: null },
      ],
      vestiaires_mixtes: false, cabines_individuelles: true, douches_individuelles: true, douches_collectives: false, cabine_pmr: true,
    },
  ]

  for (const p of piscines) {
    const horairesCreate: HoraireInput[] = p.horaires_scolaire
    ? [...p.horaires_scolaire, ...(p.horaires_vacances as HoraireInput[])]
    : [...horairesMunicipaux('SCOLAIRE'), ...horairesMunicipaux('VACANCES')]

    await prisma.piscine.create({
      data: {
        nom: p.nom,
        adresse: p.adresse,
        arrondissement: p.arrondissement,
        latitude: p.latitude,
        longitude: p.longitude,
        description: p.description,
        telephone: p.telephone,
        email: p.email ?? null,
        site_web: p.site_web ?? null,
        acces_pmr: p.acces_pmr,
        queer_friendly: p.queer_friendly,
        accepte_passe_paris: p.accepte_passe_paris,
        is_open: p.is_open,
        espace_solarium: p.espace_solarium,
        activites: p.activites,
        images_galerie: [],
        ...tarifs,
        seche_cheveux: true,
        distributeur_equipements: false,
        casiers: true,
        vestiaires_mixtes: p.vestiaires_mixtes,
        cabines_individuelles: p.cabines_individuelles,
        douches_individuelles: p.douches_individuelles,
        douches_collectives: p.douches_collectives,
        cabine_pmr: p.cabine_pmr,
        distributeur_boisson: false,
        bassins: { create: p.bassins },
        horaires_reguliers: { create: horairesCreate },
      }
    })
  }

  console.log('✓ Seed terminé — 42 piscines créées')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })